// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using deCasa.Data;

namespace deCasa.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211020215237_add-transaction-value")]
    partial class addtransactionvalue
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("deCasa.Models.Transaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("PayeeId")
                        .HasColumnType("text");

                    b.Property<string>("PayerId")
                        .HasColumnType("text");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PayeeId");

                    b.HasIndex("PayerId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("deCasa.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<decimal>("Wallet")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("deCasa.Models.LegalPerson", b =>
                {
                    b.HasBaseType("deCasa.Models.User");

                    b.Property<string>("Cnpj")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("LegalPerson");
                });

            modelBuilder.Entity("deCasa.Models.NormalPerson", b =>
                {
                    b.HasBaseType("deCasa.Models.User");

                    b.Property<string>("Cpf")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("NormalPerson");
                });

            modelBuilder.Entity("deCasa.Models.Transaction", b =>
                {
                    b.HasOne("deCasa.Models.User", "Payee")
                        .WithMany()
                        .HasForeignKey("PayeeId");

                    b.HasOne("deCasa.Models.User", "Payer")
                        .WithMany()
                        .HasForeignKey("PayerId");

                    b.Navigation("Payee");

                    b.Navigation("Payer");
                });
#pragma warning restore 612, 618
        }
    }
}
